# Generated by Django 2.2.4 on 2019-12-19 09:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeModel',
            fields=[
                ('empID', models.IntegerField(primary_key=True, serialize=False)),
                ('empName', models.CharField(max_length=30)),
                ('contactNo', models.IntegerField(max_length=10, unique=True)),
                ('emailID', models.EmailField(max_length=254, unique=True)),
                ('designation', models.CharField(max_length=30)),
                ('password', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='TaskAssigning',
            fields=[
                ('taskno', models.IntegerField(primary_key=True, serialize=False)),
                ('taskname', models.CharField(max_length=30)),
                ('empID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin_app.EmployeeModel')),
            ],
        ),
    ]
