# Generated by Django 2.2.6 on 2019-12-20 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0002_auto_20191220_1318'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeemodel',
            name='status',
            field=models.CharField(default=False, max_length=30),
        ),
    ]
