# Generated by Django 2.2.6 on 2019-12-20 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0003_employeemodel_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskassigning',
            name='taskno',
            field=models.AutoField(default=False, primary_key=True, serialize=False),
        ),
    ]
