# Generated by Django 2.2.6 on 2019-12-21 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0004_auto_20191220_2039'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskassigning',
            name='taskno',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
