# Generated by Django 2.2.6 on 2019-12-21 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0005_auto_20191221_1047'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskassigning',
            name='status',
            field=models.CharField(default=False, max_length=30),
        ),
    ]
