# Generated by Django 2.2.6 on 2019-12-21 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0006_taskassigning_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskassigning',
            name='status',
            field=models.CharField(max_length=30),
        ),
    ]
