# Generated by Django 2.2.6 on 2019-12-21 13:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0007_auto_20191221_1201'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employeemodel',
            name='status',
        ),
    ]
